#########
# DEFAULT
#########

spring:
# JPA
  jpa:
    hibernate:
      ddl-auto: update
# Security
  security:
    user:
      name: buzz
      password: infinity
# Data
  
  data:
    rest:
      base-path: /api

# Server
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

# Application
taco:
  orders:
    pageSize: 10

tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: 1L0v3T4c0s
    pollRate: 10000
  api:
    url: http://api.tacocloud.com

---

############
# PRODUCTION
############
spring:
  profiles: prod
  rabbitmq:
    host: rabbit.tacocloud.com
    port: 5673
    username: tacoweb
    password: l3tm31n
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central
      receive-timeout: 30000

logging:
  level:
    tacos: WARN
