#########
# DEFAULT
#########

spring:
# JPA
  jpa:
    hibernate:
      ddl-auto: update
# Security
  security:
    user:
      name: buzz
      password: infinity
# Data
  
  data:
    rest:
      base-path: /api

# Server
server:
  port: 8443
  ssl: 
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein

# Logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

# Application
taco:
  orders:
    pageSize: 10

---

############
# PRODUCTION
############
spring:
  profiles: prod
  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue

logging:
  level:
    tacos: WARN
